sudo: false
language: node_js
env:
- CXX="g++-4.8" NODE_FOLDER=packages/puppeteer-page-object-finder
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
node_js:
- '9'
- '8'
- '6'
script: npm install && npm run build && gulp
before_install: cd $NODE_FOLDER
notifications:
  hipchat:
    rooms:
      secure: Gh4P5gDovUqziBw99479hMRf203/8XQa++s/VtjDXmDckmw7Q/S1B92eTchmag6mqMT1kyILtOEkvltzRRiFx9zvSGqgeleRU6bKlwWecg7U2VtWH21i87IjHKwWIQJhKWXWl8ah01CuBl3yMYtRWSIR025FixxDtftxWsovjdd0oAlrmoPv74opOjP/0D6KvN2b7I08KAmfNJ+BFxH3A8jVsKXsCyEAWalGvHSQrAhsk+pePUN97zk/otoJWhTI0EQtIx4hKth057GHcQu9iYX1gr/kRH5DjxErzU0ZqcX093FE3RaoDnr0xyQX5Ko35IunIt7fHxmAQrXqwXPOOI9vvrL4CO5EjCglhp4rP7itwJxFmyAa2pUsA/DWsbB2qGJWM3r99QulqUoxTtiDurezSTeT60kpzIA0ZUcEH7ou30iguBwbGbcktwNS+REz5kXWu3Z4OyCBXkpqrr9xXRqCfTDTJ9Jm1QfY0HoZM7hQVzottlOs4zoDUEZSO85eKeEMiQyB9fJKyRMmRKT0FexeBcxYti8PvpRfC7ymVhxVIaVI2vMvF4do537TvUEcDTdYkUXgvrdtZ1ct9Yx+zmG2TtunZsfiIiZOMiW/lpMFYs07vunFF/jYlAuR47hhGX21A3i3nDeeiKHI+jze53hT6wZpXtZEn4z3NFdXwXc=
  slack:
    secure: CU1f45iN1obvyx+rmMkm6P+BLBWl40cmxRiu3CH5Hrh6EwtKLb0pFGmIRY7v3+2OABFxDqh+z7NOdJ3lkIq/jdPe1ohk1gde8qyjcDkGLoC/dND78V0txEY+AN8XQF9UHUb5RmOhIuOkbe0qs1IjVDxoWdXbgCQRskQL3k+mFVpwQ76p02WPy/H4+UKMGiPtA5q63SNg0HxemdYADtgvlIvBQwKnNE6JjzJ0gJrMkccsMQeiXTWyqw5HYAp+4IqJDk4+GjIvctthKefibM8NR5FtwqYDUv96Bni2PxCfuN3EmtxYydKQmIjP3hkj/3A/yVCuk3B21+8S9yrPxPHGiqMBR0fS6515fIsph0T0zHhhS+pU8/Z8ND6YmNbDpX1tV3jC+ol8our6YoGfv+Sj/ceBqNQena3H16iGeEXikVHsObVB1L9Mqph4RmOC59apor3VJEMuf/cj7G6Y6u6d1xw9JNtRConeq1vbRs4JoeOSaEoyI5cyceLB5eMS8QSfoTCHfZ5IxGfQfcITG/E5T30WPWgVOxOgUEhWzyVpIfgQK9Mq5hOMYRJPKSdNJZDnwz57PCj9O/aK0Dj3X4rce367vXBm6XOk5/PRsJwFSYI08RpKvZKqFyfZdzYCFKNvp/Iz5uDDqhFi/gGDuCnEUP7Vucd4umW9ycivv9APr3w=
